name: Publish Tessl Tile

permissions:
  id-token: write # Required for OIDC token
  contents: read # Required to checkout the repository

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: tesslio/publish@dcef29a61e77d536ca82c7582d5225361862a644 # latest commit as of 2026-02-20
        with:
          token: ${{ secrets.TESSL_API_TOKEN }}
